# -*- coding: utf-8 -*-
"""test_google_vecs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HWp_jgCaV4nmo_Ky-GWQEnsJt2RbryQa
"""

import gensim
import os
from google.colab import drive
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Mount the google Drive with the data
drive.mount('/content/drive')

# The data folder
datapath = '/content/drive/My Drive/COMP 550 Term Project/Data/'

# Load the KeyedVectors
vecs = gensim.models.KeyedVectors.load_word2vec_format(datapath+ 'vectors/GoogleNews-vectors-negative300.bin', binary=True)

# Test the Vectors
w1 = "fall"
print("Most similar to {0}".format(w1), vecs.most_similar(positive=w1))

w2 = "waterfall"
print("Similarity of " + w1 + " and " + w2 + ": ", vecs.similarity(w1,w2))

# Check the maximum and minimum value of a vector
vec = vecs.get_vector('hello')
print('minimum', np.amin(vec))
print('maximum', np.amax(vec))

# Load the CSVs into panda frames
df = pd.read_csv(datapath + 'training/fckn_work.csv')
errors = 0

#Add the cosine similarities to each of the rows
sim_c1stim = []
sim_c2stim = []
sim_c1c2stim = []

for index, row in df.iterrows():

  c1 = row['c1']
  c2 = row['c2']
  stim = row['stim']


  try:
    c1stim = vecs.similarity(c1,stim)
    
    c2stim = vecs.similarity(c2,stim)

    v1 = vecs.get_vector(c1)
    v2 = vecs.get_vector(c2)
    vstim = vecs.get_vector(stim)

    v1 = np.reshape(v1,(1,-1))
    v2 = np.reshape(v2,(1,-1))
    vstim = np.reshape(vstim,(1,-1))

    #print(shape1, shape2, shape3)
    c1c2stim =  cosine_similarity(np.add(v1,v2),vstim)
    #print(c1c2stim)
    sim_c1stim += [c1stim]
    # print(c1stim)
    sim_c2stim += [c2stim]
    # print(c2stim)
    c1c2stim = c1c2stim.tolist()
    # print(c1c2stim[0])
    # print(type(c1c2stim[0]))
    sim_c1c2stim += c1c2stim[0]
    

  except Exception as e:
    #print(e)
    df.drop(index,inplace=True)
    errors+=1
    continue
#print('********************',len(sim_c1stim), len(sim_c2stim), len(sim_c1c2stim))
df.insert(len(df.columns)-1,'sim_c1stim',sim_c1stim)
df.insert(len(df.columns)-1,'sim_c2stim', sim_c2stim)
df.insert(len(df.columns)-1,'sim_c1c2stim', sim_c1c2stim)

print('The dataframe has been updated to include similarity scores with {0} errors.'.format(errors))

df.to_csv(datapath+'training/positive_final.csv', index = False)

print('An updated csv has been created')

drive.flush_and_unmount()
print('All changes made in this colab session should now be visible in Drive.')